// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void Go_ReFresh(lv_event_t * e)
{
	// Your code here
}

void GO_AutoPlay(lv_event_t * e)
{
	// Your code here
}

void sc3tosc2(lv_event_t * e)
{
	// Your code here
}
