// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void draw_sdcardfile_1(lv_event_t * e);
void draw_sdcardfile_2(lv_event_t * e);
void draw_sdcardfile_3(lv_event_t * e);
void draw_sdcardfile_4(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
