// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "Arduino.h"

void draw_sdcardfile_1(lv_event_t *e)
{
	// Your code here
	//digitalWrite(26, HIGH);
	goPrev();
}

void draw_sdcardfile_2(lv_event_t *e)
{
	// Your code here
	//digitalWrite(26, LOW);
	goNext();
}

void draw_sdcardfile_3(lv_event_t *e)
{
	// Your code here
}

void draw_sdcardfile_4(lv_event_t *e)
{
	// Your code here
}
