// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "Arduino.h"

int TFTLCD_BUTTON = 0; // 因为库中不能调用自己写的函数，只能用一个变量将信息传递出去
int LaserBegin = 0;	   // 第一个按钮按下，开始工作

void Go_ReFresh(lv_event_t *e)
{
	// Your code here
	TFTLCD_BUTTON = 1;
	LaserBegin = 1;
}

void GO_AutoPlay(lv_event_t *e)
{
	// Your code here
	TFTLCD_BUTTON = 2;
	LaserBegin = 1;
}

void sc3tosc2(lv_event_t * e)
{
	// Your code here
	TFTLCD_BUTTON = 3;
}
