// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "Arduino.h"

int TFTLCD_BUTTON = 0; // 因为库中不能调用自己写的函数，只能用一个变量将信息传递出去

void draw_sdcardfile_1(lv_event_t *e)
{
	// Your code here
	// digitalWrite(26, HIGH);
	TFTLCD_BUTTON = 1;
}

void draw_sdcardfile_2(lv_event_t *e)
{
	// Your code here
	// digitalWrite(26, LOW);
	TFTLCD_BUTTON = 2;
}

void draw_sdcardfile_3(lv_event_t *e)
{
	// Your code here
	TFTLCD_BUTTON = 3;
}

void draw_sdcardfile_4(lv_event_t *e)
{
	// Your code here
	TFTLCD_BUTTON = 4;
}
