// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "Arduino.h"

int buttonState = 0;

void draw_sdcardfile_1(lv_event_t *e)
{
	// Your code here
	//digitalWrite(26, HIGH);
	buttonState = 1;
	//Serial.println("buttonL clicked");
}

void draw_sdcardfile_2(lv_event_t *e)
{
	// Your code here
	//digitalWrite(26, LOW);
	buttonState = 2;
	//Serial.println("buttonR clicked");
}

void draw_sdcardfile_3(lv_event_t *e)
{
	// Your code here
}

void draw_sdcardfile_4(lv_event_t *e)
{
	// Your code here
}
